### ISSUE TITLE
[Q&A] about the new .py files?

### ISSUE THREAD

**Issue by bachig26** [edl2/flixhq-cli#2]
I just saw the new addition to repo (akira.py and rofi.py), it lookslike using the same API of flixhq and may i know what it is?
what's the difference between them and in using them?

**Comment by bachig26** [comment]
> I just saw the new addition to repo (akira.py and rofi.py), it lookslike using the same API of flixhq and may i know what it is? what's the difference between them and in using them?

I just ran the akira.py, and it looked all three cli is same with different variant of execution of a kind (fyi, i don't know well on this topic).

I'm really curious on how can they be compared and how can I pick which one to use as default?

**Comment by edl2** [comment]
They are currently just a dumping ground for code, they will eventually be consolidated to one project, for example where you can choose between terminal or rofi selecting. i suggest just using the original file until the project is setup completely.

**Comment by bachig26** [comment]
> They are currently just a dumping ground for code, they will eventually be consolidated to one project, for example where you can choose between terminal or rofi selecting. i suggest just using the original file until the project is setup completely.

okay, thank you. 
I'm looking forward to see the complete version. good luck :)
